# production overrides for backend
podinfo:
  replicaCount: 3
  logLevel: info
  ui:
    message: "backend @ production"
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
