# production overrides for homepage
podinfo:
  replicaCount: 3
  logLevel: info
  ui:
    message: "homepage @ production"
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
